### ISSUE TITLE
Implement Conditional Debug Logging

### ISSUE THREAD

**Issue by GabrielEValenzuela** [GabrielEValenzuela/ComfyChairCpp#22]
# User Story
**As a** developer or system administrator,  
**I want** to enable detailed logging of system operations when needed by using a command-line option,  
**So that** I can debug and trace system behavior without impacting performance during normal operations.

#### Background
The current system operates without comprehensive runtime logging, making troubleshooting and detailed monitoring difficult. To enhance debugging capabilities without affecting the usual performance, we need to implement a logging system that can be enabled conditionally via a command-line argument.

#### Acceptance Criteria
1. **Command-Line Switch**: The system must accept a `-d` command-line option to enable debug mode.
2. **Log Output**: When debug mode is enabled, log detailed operations to a file, including timestamps, source file identifiers, log levels (INFO/WARN/ERROR), and descriptive messages.
3. **Log Format**: Logs should adhere to the specified format: `timestamp:file:LEVEL: Message`.
4. **Performance**: Ensure that logging has minimal performance impact when not enabled.
5. **Documentation**: Update the system documentation to include information on how to enable and use the new logging feature.

#### Tasks
- [ ] Parse the `-d` command-line argument to enable debug mode.
- [ ] Implement a logging mechanism that outputs to a file in the specified format.
- [ ] Ensure logs include all necessary details like timestamp, file, log level, and message.
- [ ] Test the logging system under various conditions to ensure it activates only when specified and captures accurate information.

#### Example Implementation in C++

Here is a basic example of how you could implement this in modern C++:

> [!WARNING]
> Use only for guide

```cpp
#include <iostream>
#include <fstream>
#include <chrono>
#include <iomanip>
#include <filesystem>
#include <sstream>

class Logger {
public:
    Logger(const std::string& filename) : logFile(filename, std::ios::app) {}

    void log(const std::string& message, const std::string& level, const std::string& file) {
        auto now = std::chrono::system_clock::now();
        auto time_t = std::chrono::system_clock::to_time_t(now);

        // Using stringstream for thread-safe logging
        std::stringstream logEntry;
        logEntry << std::put_time(std::localtime(&time_t), "%Y-%m-%d %H:%M:%S");
        logEntry << ":" << file << ":" << level << ": " << message << "\n";
        
        logFile << logEntry.str();
        logFile.flush(); // Ensure it writes to file immediately
    }

private:
    std::ofstream logFile;
};

class Application {
public:
    void run(bool debugMode) {
        Logger logger("app.log");
        if (debugMode) {
            logger.log("Starting application in debug mode", "INFO", __FILE__);
        }

        // Application logic
        if (debugMode) {
            logger.log("Application is running", "INFO", __FILE__);
        }

        // More application logic
        if (debugMode) {
            logger.log("Application finished running", "INFO", __FILE__);
        }
    }
};

int main(int argc, char* argv[]) {
    bool debugMode = false;

    for (int i = 1; i < argc; ++i) {
        if (std::string(argv[i]) == "-d") {
            debugMode = true;
            break;
        }
    }

    Application app;
    app.run(debugMode);
    return 0;
}
```

#### Potential Challenges
- **File Handling**: Ensure the log file handles simultaneous access safely if multi-threading is involved.
- **Log File Size Management**: Implement log rotation or archiving if log files become too large.

#### Impact
This enhancement will significantly improve the ability to trace and debug the system by providing detailed logs when needed, thus facilitating faster resolution of issues and better understanding of system behavior under various conditions.

---

**Comment by GabrielEValenzuela** [comment]
Out of scope.
